<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
<div class="container">
    <div class="jumbotron mt-5">
        <h1 class="display-4">Стажер PHP разработчик Alimov Filipp</h1>
        <p class="lead">Привет! Меня зовут Filipp и я Junior PHP разработчик. Я увлечен программированием и созданием веб-приложений. Мой стек технологий включает PHP, MySQL, HTML, CSS и JavaScript. Я также имею опыт работы с фреймворками, такими как Laravel и Symfony.</p>
        <hr class="my-4">
        <p>Я стремлюсь к постоянному обучению и развитию своих навыков в области веб-разработки. Я готов к новым вызовам и возможностям для роста в качестве разработчика.</p>
        <a href="/home" class="btn btn-primary">Go Home</a>
    </div>
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>
