<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <h1>Проект</h1>
        <a href="/users" class="btn btn-primary">View Users</a>
        <a href="/about" class="btn btn-primary">Go to about</a>
    </div>
</div>
</body>
</html>
