<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список пользователей</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css">
    <style>
        .container {
            width: 100%;
        }

        .table {
            width: 100%;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .table th,
        .table td {
            padding: 10px;
            border: 1px solid #ccc;
        }

        .table th {
            text-align: center;
        }

        .table tr:hover {
            background-color: #eee;
        }

        .text-center {
            text-align: center;
        }

        .btn-container {
            text-align: center;
            margin-top: 40px;
            margin-bottom: 40px;
        }
        .btn {
            border-radius: 25px;
        }

        .btn-primary {
            background-color: #007BFF;
            color: white;
            text-decoration: none !important;
            transition: background-color 0.3s ease;
            padding: 15px 30px;
            font-size: 20px;
            border: none;
            outline: none;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
<div class="container">
    <h1 class="text-center">Список пользователей</h1>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Имя</th>
            <th>E-mail</th>
            <th>JSON</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td><a href="/users/{{ user.id }}">{{ user.id }}</a></td>
            <td>{{ user.name }}</td>
            <td><a href="mailto:{{ user.email }}">{{ user.email }}</a></td>
            <td><a href="/api/users/{{ user.id }}">JSON</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="btn-container">
        <a href="/welcome" class="btn btn-primary btn-lg rounded-pill">Вернуться на главную</a>
    </div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>

</html>
