<!-- users.phtml -->
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Users</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
<div class="container">
    <h1>List of Users</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
        </tr>
        </thead>
        <tbody>
        <?php
        // Создание экземпляра Faker
        $faker = Faker\Factory::create();

        // Генерация фейковых данных пользователей
        for ($i = 0; $i < 10; $i++) {
            $name = $faker->name;
            $email = $faker->email;
            $address = $faker->address;

            echo "
                        <tr>
                            <td>$name</td>
                            <td>$email</td>
                            <td>$address</td>
                        </tr>
                    ";
        }
        ?>
        </tbody>
    </table>
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>
