<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{% block content %}
<div class="container text-center my-5">
    <h1 class="display-2">Наши пользователи</h1>
    <ul class="list-unstyled">
        <li class="mb-3"><a href="/users" class="btn btn-primary btn-lg rounded-pill">Список пользователей</a></li>
        <li><a href="/api/users" class="btn btn-primary btn-lg rounded-pill">Список пользователей (JSON)</a></li>
    </ul>
</div>
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>
